package ly.img.react_native.vesdk.effects;

import ly.img.android.pesdk.assets.filter.basic.R.drawable;
import ly.img.android.pesdk.assets.filter.basic.R.string;
import ly.img.android.pesdk.backend.decoder.ImageSource;
import ly.img.android.pesdk.ui.panels.item.AbstractIdItem;
import ly.img.android.pesdk.ui.panels.item.FilterItem;
import ly.img.android.pesdk.ui.utils.DataSourceIdItemList;
import ly.img.react_native.vesdk.R;
import ly.img.react_native.vesdk.view.CustomFilterItem;
import ly.img.react_native.vesdk.view.CustomFolderItem;

public class CustomFilterPack {
    public CustomFilterPack() {
    }

    public static DataSourceIdItemList<AbstractIdItem> getFilterPack() {
        DataSourceIdItemList<AbstractIdItem> filterList = new DataSourceIdItemList();
        DataSourceIdItemList<FilterItem> folderList = new DataSourceIdItemList();
        filterList.add(new CustomFilterItem("imgly_filter_none", R.string.pesdk_filter_asset_none));
        folderList.add(new CustomFilterItem("imgly_duotone_desert", string.pesdk_filter_asset_duotoneDesert));
        folderList.add(new CustomFilterItem("imgly_duotone_peach", string.pesdk_filter_asset_duotonePeach));
        folderList.add(new CustomFilterItem("imgly_duotone_clash", string.pesdk_filter_asset_duotoneClash));
        folderList.add(new CustomFilterItem("imgly_duotone_plum", string.pesdk_filter_asset_duotonePlum));
        folderList.add(new CustomFilterItem("imgly_duotone_breezy", string.pesdk_filter_asset_duotoneBreezy));
        folderList.add(new CustomFilterItem("imgly_duotone_deepblue", string.pesdk_filter_asset_duotoneDeepBlue));
        folderList.add(new CustomFilterItem("imgly_duotone_frog", string.pesdk_filter_asset_duotoneFrog));
        folderList.add(new CustomFilterItem("imgly_duotone_sunset", string.pesdk_filter_asset_duotoneSunset));
        filterList.add(new CustomFolderItem("imgly_filter_category_duotone", string.pesdk_filter_folder_duotone, ImageSource.create(drawable.pesdk_filter_category_duotone), folderList));
        folderList.clear();
        folderList.add(new CustomFilterItem("imgly_lut_ad1920", string.pesdk_filter_asset_ad1920));
        folderList.add(new CustomFilterItem("imgly_lut_bw", string.pesdk_filter_asset_bw));
        folderList.add(new CustomFilterItem("imgly_lut_x400", string.pesdk_filter_asset_x400));
        folderList.add(new CustomFilterItem("imgly_lut_litho", string.pesdk_filter_asset_litho));
        folderList.add(new CustomFilterItem("imgly_lut_sepiahigh", string.pesdk_filter_asset_sepiaHigh));
        folderList.add(new CustomFilterItem("imgly_lut_plate", string.pesdk_filter_asset_plate));
        folderList.add(new CustomFilterItem("imgly_lut_sin", string.pesdk_filter_asset_sin));
        filterList.add(new CustomFolderItem("imgly_filter_category_bw", string.pesdk_filter_folder_b_and_w, ImageSource.create(drawable.pesdk_filter_category_b_w), folderList));
        folderList.clear();
        folderList.add(new CustomFilterItem("imgly_lut_blues", string.pesdk_filter_asset_blues));
        folderList.add(new CustomFilterItem("imgly_lut_front", string.pesdk_filter_asset_front));
        folderList.add(new CustomFilterItem("imgly_lut_texas", string.pesdk_filter_asset_texas));
        folderList.add(new CustomFilterItem("imgly_lut_celsius", string.pesdk_filter_asset_celsius));
        folderList.add(new CustomFilterItem("imgly_lut_cool", string.pesdk_filter_asset_cool));
        filterList.add(new CustomFolderItem("imgly_filter_category_vintage", string.pesdk_filter_folder_vintage, ImageSource.create(drawable.pesdk_filter_category_vintage), folderList));
        folderList.clear();
        folderList.add(new CustomFilterItem("imgly_lut_chest", string.pesdk_filter_asset_chest));
        folderList.add(new CustomFilterItem("imgly_lut_winter", string.pesdk_filter_asset_winter));
        folderList.add(new CustomFilterItem("imgly_lut_kdynamic", string.pesdk_filter_asset_dynamic));
        folderList.add(new CustomFilterItem("imgly_lut_fall", string.pesdk_filter_asset_fall));
        folderList.add(new CustomFilterItem("imgly_lut_lenin", string.pesdk_filter_asset_lenin));
        folderList.add(new CustomFilterItem("imgly_lut_pola669", string.pesdk_filter_asset_669));
        filterList.add(new CustomFolderItem("imgly_filter_category_smooth", string.pesdk_filter_folder_smooth, ImageSource.create(drawable.pesdk_filter_category_smooth), folderList));
        folderList.clear();
        folderList.add(new CustomFilterItem("imgly_lut_elder", string.pesdk_filter_asset_elder));
        folderList.add(new CustomFilterItem("imgly_lut_orchid", string.pesdk_filter_asset_orchid));
        folderList.add(new CustomFilterItem("imgly_lut_bleached", string.pesdk_filter_asset_bleached));
        folderList.add(new CustomFilterItem("imgly_lut_bleachedblue", string.pesdk_filter_asset_bBlue));
        folderList.add(new CustomFilterItem("imgly_lut_breeze", string.pesdk_filter_asset_breeze));
        folderList.add(new CustomFilterItem("imgly_lut_blueshadows", string.pesdk_filter_asset_blueShade));
        filterList.add(new CustomFolderItem("imgly_filter_category_cold", string.pesdk_filter_folder_cold, ImageSource.create(drawable.pesdk_filter_category_cold), folderList));
        folderList.clear();
        folderList.add(new CustomFilterItem("imgly_lut_sunset", string.pesdk_filter_asset_sunset));
        folderList.add(new CustomFilterItem("imgly_lut_eighties", string.pesdk_filter_asset_80s));
        folderList.add(new CustomFilterItem("imgly_lut_evening", string.pesdk_filter_asset_evening));
        folderList.add(new CustomFilterItem("imgly_lut_k2", string.pesdk_filter_asset_k2));
        folderList.add(new CustomFilterItem("imgly_lut_nogreen", string.pesdk_filter_asset_noGreen));
        filterList.add(new CustomFolderItem("imgly_filter_category_warm", string.pesdk_filter_folder_warm, ImageSource.create(drawable.pesdk_filter_category_warm), folderList));
        folderList.clear();
        folderList.add(new CustomFilterItem("imgly_lut_ancient", string.pesdk_filter_asset_ancient));
        folderList.add(new CustomFilterItem("imgly_lut_cottoncandy", string.pesdk_filter_asset_candy));
        folderList.add(new CustomFilterItem("imgly_lut_classic", string.pesdk_filter_asset_classic));
        folderList.add(new CustomFilterItem("imgly_lut_colorful", string.pesdk_filter_asset_colorful));
        folderList.add(new CustomFilterItem("imgly_lut_creamy", string.pesdk_filter_asset_creamy));
        folderList.add(new CustomFilterItem("imgly_lut_fixie", string.pesdk_filter_asset_fixie));
        folderList.add(new CustomFilterItem("imgly_lut_food", string.pesdk_filter_asset_food));
        folderList.add(new CustomFilterItem("imgly_lut_fridge", string.pesdk_filter_asset_fridge));
        folderList.add(new CustomFilterItem("imgly_lut_clam", string.pesdk_filter_asset_glam));
        folderList.add(new CustomFilterItem("imgly_lut_gobblin", string.pesdk_filter_asset_goblin));
        folderList.add(new CustomFilterItem("imgly_lut_highcontrast", string.pesdk_filter_asset_hicon));
        folderList.add(new CustomFilterItem("imgly_lut_highcarb", string.pesdk_filter_asset_carb));
        folderList.add(new CustomFilterItem("imgly_lut_k1", string.pesdk_filter_asset_k1));
        folderList.add(new CustomFilterItem("imgly_lut_k6", string.pesdk_filter_asset_k6));
        folderList.add(new CustomFilterItem("imgly_lut_keen", string.pesdk_filter_asset_keen));
        folderList.add(new CustomFilterItem("imgly_lut_lomo", string.pesdk_filter_asset_lomo));
        folderList.add(new CustomFilterItem("imgly_lut_lomo100", string.pesdk_filter_asset_lomo100));
        folderList.add(new CustomFilterItem("imgly_lut_lucid", string.pesdk_filter_asset_lucid));
        folderList.add(new CustomFilterItem("imgly_lut_mellow", string.pesdk_filter_asset_mellow));
        folderList.add(new CustomFilterItem("imgly_lut_neat", string.pesdk_filter_asset_neat));
        folderList.add(new CustomFilterItem("imgly_lut_pale", string.pesdk_filter_asset_pale));
        folderList.add(new CustomFilterItem("imgly_lut_pitched", string.pesdk_filter_asset_pitched));
        folderList.add(new CustomFilterItem("imgly_lut_polasx", string.pesdk_filter_asset_sx));
        folderList.add(new CustomFilterItem("imgly_lut_pro400", string.pesdk_filter_asset_pro400));
        folderList.add(new CustomFilterItem("imgly_lut_quozi", string.pesdk_filter_asset_quozi));
        folderList.add(new CustomFilterItem("imgly_lut_settled", string.pesdk_filter_asset_settled));
        folderList.add(new CustomFilterItem("imgly_lut_seventies", string.pesdk_filter_asset_70s));
        folderList.add(new CustomFilterItem("imgly_lut_soft", string.pesdk_filter_asset_soft));
        folderList.add(new CustomFilterItem("imgly_lut_steel", string.pesdk_filter_asset_steel));
        folderList.add(new CustomFilterItem("imgly_lut_summer", string.pesdk_filter_asset_summer));
        folderList.add(new CustomFilterItem("imgly_lut_tender", string.pesdk_filter_asset_tender));
        folderList.add(new CustomFilterItem("imgly_lut_twilight", string.pesdk_filter_asset_twilight));
        filterList.add(new CustomFolderItem("imgly_filter_category_legacy", string.pesdk_filter_folder_legacy, ImageSource.create(drawable.pesdk_filter_category_legacy), folderList));
        folderList.clear();
        return filterList;
    }
}
