package ly.img.react_native.vesdk.effects;

import ly.img.android.pesdk.backend.decoder.ImageSource;
import ly.img.android.pesdk.ui.panels.item.AbstractIdItem;
import ly.img.android.pesdk.ui.panels.item.FilterItem;
import ly.img.android.pesdk.ui.utils.DataSourceIdItemList;
import ly.img.react_native.vesdk.R;
import ly.img.react_native.vesdk.view.CustomFilterItem;
import ly.img.react_native.vesdk.view.CustomFolderItem;

public class CustomFilterPack {
    public CustomFilterPack() {
    }

    public static DataSourceIdItemList<AbstractIdItem> getFilterPack() {
        DataSourceIdItemList<AbstractIdItem> filterList = new DataSourceIdItemList();
        DataSourceIdItemList<FilterItem> folderList = new DataSourceIdItemList();
        filterList.add(new CustomFilterItem("imgly_filter_none", R.string.pesdk_filter_asset_none));
        folderList.add(new CustomFilterItem("imgly_duotone_desert", R.string.pesdk_filter_asset_duotoneDesert));
        folderList.add(new CustomFilterItem("imgly_duotone_peach", R.string.pesdk_filter_asset_duotonePeach));
        folderList.add(new CustomFilterItem("imgly_duotone_clash", R.string.pesdk_filter_asset_duotoneClash));
        folderList.add(new CustomFilterItem("imgly_duotone_plum", R.string.pesdk_filter_asset_duotonePlum));
        folderList.add(new CustomFilterItem("imgly_duotone_breezy", R.string.pesdk_filter_asset_duotoneBreezy));
        folderList.add(new CustomFilterItem("imgly_duotone_deepblue", R.string.pesdk_filter_asset_duotoneDeepBlue));
        folderList.add(new CustomFilterItem("imgly_duotone_frog", R.string.pesdk_filter_asset_duotoneFrog));
        folderList.add(new CustomFilterItem("imgly_duotone_sunset", R.string.pesdk_filter_asset_duotoneSunset));
        filterList.add(new CustomFolderItem("imgly_filter_category_duotone", R.string.pesdk_filter_folder_duotone, ImageSource.create(R.drawable.pesdk_filter_category_duotone), folderList));
        folderList.clear();
        folderList.add(new CustomFilterItem("imgly_lut_ad1920", R.string.pesdk_filter_asset_ad1920));
        folderList.add(new CustomFilterItem("imgly_lut_bw", R.string.pesdk_filter_asset_bw));
        folderList.add(new CustomFilterItem("imgly_lut_x400", R.string.pesdk_filter_asset_x400));
        folderList.add(new CustomFilterItem("imgly_lut_litho", R.string.pesdk_filter_asset_litho));
        folderList.add(new CustomFilterItem("imgly_lut_sepiahigh", R.string.pesdk_filter_asset_sepiaHigh));
        folderList.add(new CustomFilterItem("imgly_lut_plate", R.string.pesdk_filter_asset_plate));
        folderList.add(new CustomFilterItem("imgly_lut_sin", R.string.pesdk_filter_asset_sin));
        filterList.add(new CustomFolderItem("imgly_filter_category_bw", R.string.pesdk_filter_folder_b_and_w, ImageSource.create(R.drawable.pesdk_filter_category_b_w), folderList));
        folderList.clear();
        folderList.add(new CustomFilterItem("imgly_lut_blues", R.string.pesdk_filter_asset_blues));
        folderList.add(new CustomFilterItem("imgly_lut_front", R.string.pesdk_filter_asset_front));
        folderList.add(new CustomFilterItem("imgly_lut_texas", R.string.pesdk_filter_asset_texas));
        folderList.add(new CustomFilterItem("imgly_lut_celsius", R.string.pesdk_filter_asset_celsius));
        folderList.add(new CustomFilterItem("imgly_lut_cool", R.string.pesdk_filter_asset_cool));
        filterList.add(new CustomFolderItem("imgly_filter_category_vintage", R.string.pesdk_filter_folder_vintage, ImageSource.create(R.drawable.pesdk_filter_category_vintage), folderList));
        folderList.clear();
        folderList.add(new CustomFilterItem("imgly_lut_chest", R.string.pesdk_filter_asset_chest));
        folderList.add(new CustomFilterItem("imgly_lut_winter", R.string.pesdk_filter_asset_winter));
        folderList.add(new CustomFilterItem("imgly_lut_kdynamic", R.string.pesdk_filter_asset_dynamic));
        folderList.add(new CustomFilterItem("imgly_lut_fall", R.string.pesdk_filter_asset_fall));
        folderList.add(new CustomFilterItem("imgly_lut_lenin", R.string.pesdk_filter_asset_lenin));
        folderList.add(new CustomFilterItem("imgly_lut_pola669", R.string.pesdk_filter_asset_669));
        filterList.add(new CustomFolderItem("imgly_filter_category_smooth", R.string.pesdk_filter_folder_smooth, ImageSource.create(R.drawable.pesdk_filter_category_smooth), folderList));
        folderList.clear();
        folderList.add(new CustomFilterItem("imgly_lut_elder", R.string.pesdk_filter_asset_elder));
        folderList.add(new CustomFilterItem("imgly_lut_orchid", R.string.pesdk_filter_asset_orchid));
        folderList.add(new CustomFilterItem("imgly_lut_bleached", R.string.pesdk_filter_asset_bleached));
        folderList.add(new CustomFilterItem("imgly_lut_bleachedblue", R.string.pesdk_filter_asset_bBlue));
        folderList.add(new CustomFilterItem("imgly_lut_breeze", R.string.pesdk_filter_asset_breeze));
        folderList.add(new CustomFilterItem("imgly_lut_blueshadows", R.string.pesdk_filter_asset_blueShade));
        filterList.add(new CustomFolderItem("imgly_filter_category_cold", R.string.pesdk_filter_folder_cold, ImageSource.create(R.drawable.pesdk_filter_category_cold), folderList));
        folderList.clear();
        folderList.add(new CustomFilterItem("imgly_lut_sunset", R.string.pesdk_filter_asset_sunset));
        folderList.add(new CustomFilterItem("imgly_lut_eighties", R.string.pesdk_filter_asset_80s));
        folderList.add(new CustomFilterItem("imgly_lut_evening", R.string.pesdk_filter_asset_evening));
        folderList.add(new CustomFilterItem("imgly_lut_k2", R.string.pesdk_filter_asset_k2));
        folderList.add(new CustomFilterItem("imgly_lut_nogreen", R.string.pesdk_filter_asset_noGreen));
        filterList.add(new CustomFolderItem("imgly_filter_category_warm", R.string.pesdk_filter_folder_warm, ImageSource.create(R.drawable.pesdk_filter_category_warm), folderList));
        folderList.clear();
        folderList.add(new CustomFilterItem("imgly_lut_ancient", R.string.pesdk_filter_asset_ancient));
        folderList.add(new CustomFilterItem("imgly_lut_cottoncandy", R.string.pesdk_filter_asset_candy));
        folderList.add(new CustomFilterItem("imgly_lut_classic", R.string.pesdk_filter_asset_classic));
        folderList.add(new CustomFilterItem("imgly_lut_colorful", R.string.pesdk_filter_asset_colorful));
        folderList.add(new CustomFilterItem("imgly_lut_creamy", R.string.pesdk_filter_asset_creamy));
        folderList.add(new CustomFilterItem("imgly_lut_fixie", R.string.pesdk_filter_asset_fixie));
        folderList.add(new CustomFilterItem("imgly_lut_food", R.string.pesdk_filter_asset_food));
        folderList.add(new CustomFilterItem("imgly_lut_fridge", R.string.pesdk_filter_asset_fridge));
        folderList.add(new CustomFilterItem("imgly_lut_clam", R.string.pesdk_filter_asset_glam));
        folderList.add(new CustomFilterItem("imgly_lut_gobblin", R.string.pesdk_filter_asset_goblin));
        folderList.add(new CustomFilterItem("imgly_lut_highcontrast", R.string.pesdk_filter_asset_hicon));
        folderList.add(new CustomFilterItem("imgly_lut_highcarb", R.string.pesdk_filter_asset_carb));
        folderList.add(new CustomFilterItem("imgly_lut_k1", R.string.pesdk_filter_asset_k1));
        folderList.add(new CustomFilterItem("imgly_lut_k6", R.string.pesdk_filter_asset_k6));
        folderList.add(new CustomFilterItem("imgly_lut_keen", R.string.pesdk_filter_asset_keen));
        folderList.add(new CustomFilterItem("imgly_lut_lomo", R.string.pesdk_filter_asset_lomo));
        folderList.add(new CustomFilterItem("imgly_lut_lomo100", R.string.pesdk_filter_asset_lomo100));
        folderList.add(new CustomFilterItem("imgly_lut_lucid", R.string.pesdk_filter_asset_lucid));
        folderList.add(new CustomFilterItem("imgly_lut_mellow", R.string.pesdk_filter_asset_mellow));
        folderList.add(new CustomFilterItem("imgly_lut_neat", R.string.pesdk_filter_asset_neat));
        folderList.add(new CustomFilterItem("imgly_lut_pale", R.string.pesdk_filter_asset_pale));
        folderList.add(new CustomFilterItem("imgly_lut_pitched", R.string.pesdk_filter_asset_pitched));
        folderList.add(new CustomFilterItem("imgly_lut_polasx", R.string.pesdk_filter_asset_sx));
        folderList.add(new CustomFilterItem("imgly_lut_pro400", R.string.pesdk_filter_asset_pro400));
        folderList.add(new CustomFilterItem("imgly_lut_quozi", R.string.pesdk_filter_asset_quozi));
        folderList.add(new CustomFilterItem("imgly_lut_settled", R.string.pesdk_filter_asset_settled));
        folderList.add(new CustomFilterItem("imgly_lut_seventies", R.string.pesdk_filter_asset_70s));
        folderList.add(new CustomFilterItem("imgly_lut_soft", R.string.pesdk_filter_asset_soft));
        folderList.add(new CustomFilterItem("imgly_lut_steel", R.string.pesdk_filter_asset_steel));
        folderList.add(new CustomFilterItem("imgly_lut_summer", R.string.pesdk_filter_asset_summer));
        folderList.add(new CustomFilterItem("imgly_lut_tender", R.string.pesdk_filter_asset_tender));
        folderList.add(new CustomFilterItem("imgly_lut_twilight", R.string.pesdk_filter_asset_twilight));
        filterList.add(new CustomFolderItem("imgly_filter_category_legacy", R.string.pesdk_filter_folder_legacy, ImageSource.create(R.drawable.pesdk_filter_category_legacy), folderList));
        folderList.clear();
        return filterList;
    }
}
